name = "quickbooks"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "5313f8b98e20a8915418b2683ad7278c"
workers_dev = true

[observability.logs]
enabled = true
invocation_logs = true

[[kv_namespaces]]
binding = "QBO_TOKENS"
id = "49d0ca1276af457d80907876b2c53775"

# ============ TEST ENVIRONMENT ============
[env.test]
name = "quickbooks-test"

[env.test.observability.logs]
enabled = true
invocation_logs = true

[[env.test.kv_namespaces]]
binding = "QBO_TOKENS"
id = "49d0ca1276af457d80907876b2c53775"
